- name: Create temporary workplace
  file:
    path: "{{ ocp_working_dir }}"
    state: directory

- name: Download ocp install and extract
  unarchive:
    src: "{{ ocp_install_url }}"
    dest: "{{ ocp_working_dir}}"
    remote_src: yes
  register: install_file

- name: Download ocp client and extract
  unarchive:
    src: "{{ ocp_client_url }}"
    dest: "{{ ocp_working_dir}}"
    remote_src: yes
  register: client_file

- name: Create install-cofng.yaml from template
  template:
    src: install-config.yaml.j2
    dest: "{{ ocp_working_dir }}/install-config.yaml"

- name: Create manifest from configs
  command: "{{ ocp_working_dir }}/openshift-install create manifests --dir={{ ocp_working_dir }}"

- name: Edit manifest
  replace:
    regexp: "mastersSchedulable: true"
    path: "{{ ocp_working_dir }}/manifests/cluster-scheduler-02-config.yml"
    replace: "mastersSchedulable: false"

- name: Create manifest from configs
  command: "{{ ocp_working_dir }}/openshift-install create ignition-configs --dir={{ ocp_working_dir }}"

- name: Create vms
  include_tasks: start_vms.yml
  when: item[0] == item[1]['ocp_vm_type']
  with_nested:
    - ['bootstrap', 'master', 'worker']
    - '{{ vms }}'


# TODO: Clear tmp workplace
