---
- block:
  - name: Login to oVirt
    ovirt_auth:
      url: "{{ engine_url | default(lookup('env','OVIRT_URL')) | default(omit) }}"
      hostname: "{{ engine_fqdn | default(lookup('env','OVIRT_HOSTNAME')) | default(omit) }}"
      username: "{{ engine_user | default(lookup('env','OVIRT_USERNAME')) | default(omit) }}"
      password: "{{ engine_password | default(lookup('env','OVIRT_PASSWORD')) | default(omit) }}"
      ca_file: "{{ engine_cafile | default(lookup('env','OVIRT_CAFILE')) | default(omit) }}"
      insecure: "{{ engine_insecure | default(true) }}"
    when: ovirt_auth is undefined or not ovirt_auth
    register: loggedin

  - name: Include set_default_facts
    include_tasks: set_default_facts.yml

  - name: Get template info
    ovirt_template_info:
      auth: "{{ ovirt_auth }}"
      pattern: name={{ template_name }} and cluster={{ template_cluster }}
    register: template_info

  - name: Include create_template
    include_tasks: create_template.yml
    when: not template_info.ovirt_templates

  - name: Create VMs
    include_role:
      name: ovirt.vm-infra

  - name: Include install_ocp
    include_tasks: install_ocp.yml

  always:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      when: not loggedin.skipped | default(false)
