---
- name: Set default profile vms
  set_fact:
    ocp_profile: "{{ ocp_profile | combine(ocp_vms) }}"
  when: ocp_vms is defined

- name: Set default template facts
  set_fact:
    template_cluster: "{{ ocp_profile['cluster'] | default(template_cluster) | default(omit) }}"
    template_disk_storage: "{{ ocp_profile['storage_domain'] | default(template_disk_storage) | default(omit) }}"

- name: Set profile to vms
  set_fact: 
    vms: "{{ vms | map('combine', {'profile':ocp_profile}) | list }}"
