- name: Wait for VMs to be added
  async_status: "jid={{ job.ansible_job_id }}"
  register: job_result
  with_items: "{{ started_vms }}"
  loop_control:
    loop_var: job
  when: started_vms is defined and started_vms != [] and previous_value != item[0]
  until: job_result.finished
  retries: "{{ (vm_infra_create_all_timeout|int // vm_infra_create_poll_interval) + 1  }}"
  delay: "{{ vm_infra_create_poll_interval }}"

- name: Read file '{{ item[0] }}.ign' on remote host
  slurp:
    src: "{{ ocp_working_dir + '/'+item[0]+'.ign' }}"
  register: mounts
  no_log: true

- name: Create {{ item[0] }} VM
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cluster: "{{ ocp_profile['cluster'] }}"
    name: "{{ item[1]['name'] }}"
    state: running
    cloud_init_persist: True
    cloud_init:
      custom_script: "{{ mounts['content'] | b64decode | string }}"
    nics: "{{ item[1]['nics'] }}"
    timeout: "{{ vm_infra_create_single_timeout }}"
  changed_when: false
  async: "{{ vm_infra_create_single_timeout }}"
  poll: 0
  register: started_vm

- set_fact:
    started_vms: "{{ started_vms | default([]) + [started_vm] }}"
  when: previous_value == item[0]

- set_fact:
    started_vms: "{{ [started_vm] }}"
  when: previous_value != item[0]

- name: Update previous_value 
  set_fact:
    previous_value: "{{ item[0] }}"
