---
- name: oVirt infra
  hosts: localhost
  connection: local
  vars:
    engine_url: https://server/ovirt-engine/api
    engine_user: admin@internal
    engine_password: 123456

    ocp_vms:
      storage_domain: "mynfs"
      cluster: "cluster"
      template_memory: 16GiB

    vms:
      - name: master1
        ocp_vm_type: master
      - name: master2
        ocp_vm_type: master
      - name: master3
        ocp_vm_type: master
      - name: node1
        ocp_vm_type: node
      - name: node2
        ocp_vm_type: node
  roles:
    - ovirt.openshift
